name: NeigeItems
main: pers.neige.neigeitems.taboolib.platform.BukkitPlugin
version: ${version}

authors:
  - 'Neige'

softdepend:
  - 'ProtocolLib'
  - 'PlaceholderAPI'
  - 'MythicMobs'
  - 'Oraxen'
  - 'Vault'

api-version: 1.13
